### PR TITLE
Added "all english words" to wordlist and removed all duplicates

### PR DESCRIPTION
**Pull request by SleepingPig35**
Added all English words from https://github.com/dwyl/english-words and removed all duplicates from the original wordlist.

### CODE REVIEW

**Comment by kuel27** [comment]
Unfortunately, this isn't a good idea because that list contains many non-existent words, and scanning half a million words causes significant lag in JavaScript. You can try it yourself by replacing the URL of my repository with yours.

**Comment by SleepingPig35** [comment]
It works for me, I replaced the repo in the script - there is no lag maybe, its my PC?

**Comment by SleepingPig35** [comment]
Can you try it?

**Comment by kuel27** [comment]
Are you sure you changed both 'fetchAndStoreLatestWordlist' and 'exportNewWords'? I doubt it wouldn't cause lag.

**Comment by SleepingPig35** [comment]
It still works, there isn't much lag but I'm running on 64gb of RAM on an i9 so idk

**Comment by SleepingPig35** [comment]
Just tested this new edit on my old pc: it lagged so I'm closing this.

**Pull request closed without merging**
